name: Flask App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main


jobs:
    test:
        runs-on: self-hosted

        steps:
            - name: Checking out the code 
              uses : actions/checkout@v2

            - name: Pulling Docker images
              run: | 
                docker run -d -p 8001:8001 --name flask-app-02 mishrrayush/learning-repo:fixed
    
    test2: 
        runs-on: self-hosted
        needs: test

        steps:
            - name: Executing the container 
              run: | 
                docker exec -it flask-app-02 /bin/bash
            - name: testing inside the container 
              run: | 
                pytest test_app.py
            - name: Exit
              run: exit 
              
               
               

                

