name: Flask App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main


jobs:
    test:
        runs-on: self-hosted

        steps:
            - name: Checking out the code 
              uses : actions/checkout@v2

            - name: Pushing Docker images 
              run: | 
                docker build . --tag mishrrayush/learning-repo:flaskapplatest
            - name: Pulling Docker images
              run: | 
                docker run -p 5000:5000 --name flask-container mishrrayush/learning-repo:flaskapplatest 
            - name: Executing the App 
              run: | 
               docker exec flask container
               docker exec pytest test_app.py
               
               

                

